name: hello baby
age: 24

eureka:
  defaultZone: http://admin:123456@localhost:8761/eureka/,http://admin:123456@localhost:8762/eureka/
  user:
    name: admin
    password: 123456

spring:
  redis:
    host: localhost
    port: 6379
    password: Handhand123
    timeout: 60
